---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: pgsql
  clusterIP: None
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  serviceName: "postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      terminationGracePeriodSeconds: 90
      containers:
      - name: postgresql
        image: postgres:9.6
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: puppetdb-secrets
              key: postgresql-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: puppetdb-secrets
              key: postgresql-password
        - name: POSTGRES_DB
          value: puppetdb
        ports:
        - containerPort: 5432
          name: pgsql
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi